spring.application.name=onepiece-api

spring.datasource.url=jdbc:h2:mem:onepiece
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,metrics